version: "2"

services:
  application:
    image: tianon/true
    volumes:
      - "./web:/usr/src/app"
  node:
    build: "./docker/node"
    volumes_from:
      - application
    ports:
     - '8080:8080'
    networks:  
      default:
        aliases:
          - "nocker.node"
networks:
  default:
    driver: bridge